FROM node:18-alpine

# create work directory in app folder
WORKDIR /code

# install required packages for node image
RUN apk --no-cache add openssh g++ make python3 git

# copy over package.json files
COPY package.json /code/
COPY package-lock.json /code/

# install all depencies
RUN npm install --save @rollup/rollup-linux-x64-musl && npm ci

# copy over all files to the work directory
ADD . /code

# build the project
RUN npm run build

# expose the host and port 3000 to the server
ENV HOST 0.0.0.0
EXPOSE 8080

# run the build project with node
ENTRYPOINT ["node", ".dist/index.js"]